// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgyZWU_Swxwdao6kEQ9LhP9YIipx6zrUU',
    appId: '1:816853546492:web:973ada0590b78aa8d5ae79',
    messagingSenderId: '816853546492',
    projectId: 'clean-arch-app-91539',
    authDomain: 'clean-arch-app-91539.firebaseapp.com',
    storageBucket: 'clean-arch-app-91539.firebasestorage.app',
    measurementId: 'G-PK9HPTTH3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEP-ic0n11c_54QiO9Y_jgRpNEN0n84O8',
    appId: '1:816853546492:android:d0d8c9f2453d8c31d5ae79',
    messagingSenderId: '816853546492',
    projectId: 'clean-arch-app-91539',
    storageBucket: 'clean-arch-app-91539.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiuPSnRDmSS_QRFq8ZOFwNZG6Kldk7ubk',
    appId: '1:816853546492:ios:122b860cbf7340c5d5ae79',
    messagingSenderId: '816853546492',
    projectId: 'clean-arch-app-91539',
    storageBucket: 'clean-arch-app-91539.firebasestorage.app',
    iosBundleId: 'com.example.cleanArchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiuPSnRDmSS_QRFq8ZOFwNZG6Kldk7ubk',
    appId: '1:816853546492:ios:122b860cbf7340c5d5ae79',
    messagingSenderId: '816853546492',
    projectId: 'clean-arch-app-91539',
    storageBucket: 'clean-arch-app-91539.firebasestorage.app',
    iosBundleId: 'com.example.cleanArchApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgyZWU_Swxwdao6kEQ9LhP9YIipx6zrUU',
    appId: '1:816853546492:web:32703a9c203d7d63d5ae79',
    messagingSenderId: '816853546492',
    projectId: 'clean-arch-app-91539',
    authDomain: 'clean-arch-app-91539.firebaseapp.com',
    storageBucket: 'clean-arch-app-91539.firebasestorage.app',
    measurementId: 'G-8QBWRVH3LF',
  );

}